# Generated by Django 4.1.7 on 2023-04-21 16:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
